### ISSUE TITLE
[Design] 공용 컴포넌트 - 키워드 라벨 구현

### ISSUE THREAD

**Issue by Naknakk** [Team-WSS/WSS-iOS#141]
## 🛠 Issue

공용 컴포넌트인 키워드 라벨을 구현합니다.

## 📝 To-do

- [x] KeywordLabel With X -> x 누르면 수행할 작업 필요  (ex 상세 검색의 선택된 키워드 상단 리스트)
- [x] KeywordLabel Selectable -> unselected / selected 상태에 따라 변함 (ex 상세 검색의 키워드 검색결과)
- [x] KeywordLabel -> 단순히 보여주기 위한 Label (ex 작품 상세의 키워드)
