### ISSUE TITLE
[Chore] Font 변경&추가사항 반영, 컬러 에셋 추가

### ISSUE THREAD

**Issue by Naknakk** [Team-WSS/WSS-iOS#151]
## 🛠 Issue

Font 변경&추가사항 반영 겸 편의 메서드를 추가합니다.

## 📝 To-do

- [x] Font 변경&추가사항 반영
- [x] Font를 설정하면서 행간자간을 한번에 설정할 수 있도록, UILabel Extension에 메서드를 추가
- [x] Color 변경사항 적용
