### ISSUE TITLE
[Feat] 마이페이지 TodoList 정리

### ISSUE THREAD

**Issue by ena-isme** [Team-WSS/WSS-iOS#194]
## 🛠 Issue

각각의 branch merge 이후 할 일들을 정리해둡니다

## 📝 To-do

- [ ] myPage - navigationTitle 타인일 때 분기처리
- [ ] myPageDeleteID - textView text Height 적용
- [ ] myPageEdit - textView text Height 적용
- [ ] 드롭다운 에러 해결
- [x] Trash 폴더에 옮기기
