### ISSUE TITLE
[Docs] 1차 과제를 위한 README 작성

### ISSUE THREAD

**Issue by Naknakk** [Team-WSS/WSS-iOS#20]
## 🛠 Issue
- README를 작성합니당

## 📝 To-do

- [x] 간단한 프로젝트 설명 
- [x] 참여 구성원 및 구성원 사진
- [x] Coding Convention
- [x] Git branch 전략
- [x] 프로젝트 폴더링 Convention

**Comment by chetseoo** [comment]
브라이언도 울고갈 정리왕 낙낙 최고 🙌

**Comment by ena-isme** [comment]
브라이언 : 엉엉
