### ISSUE TITLE
[Design] NovelDetail Header UI 구현 - 디자인 수정 반영

### ISSUE THREAD

**Issue by Naknakk** [Team-WSS/WSS-iOS#206]
## 🛠 Issue

NovelDetail Header UI의 바뀐 부분을 다시 반영합니다.

## 📝 To-do

- [x] 배경 그라디언트 색 수정
- [x] 뱃지 하얀 배경까지 같이 내려오므로, 그렇게 수정
- [x] 읽기상태 선택 뷰 디자인 적용
- [x] 관심 / 리뷰 뷰 변경
