### ISSUE TITLE
[Network&Feat] NovelDetail API 연결 및 기능구현

### ISSUE THREAD

**Issue by Naknakk** [Team-WSS/WSS-iOS#220]
## 🛠 Issue

NovelDetail View의 API를 모두 연결합니다.
API와 연결된 기능들을 구현합니다.

## 📝 To-do

- [x] 작품정보 조회(기본) API 연결
- [x] 작품정보 조회(정보) API 연결
- [x] 관심있어요 등록&삭제 API 연결
- [x] 뷰 연결 준비!
