### ISSUE TITLE
[Feat] HomeVIew 내 4개 영역 클릭 이벤트 추가

### ISSUE THREAD

**Issue by Guryss** [Team-WSS/WSS-iOS#231]
## 🛠 Issue
- 홈뷰 내 4가지 영역에 대한 클릭 이벤트를 구현합니다. 

## 📝 To-do

- [x] 오늘의 인기작 -> 작품 정보
- [x] 지금 뜨는 수다글 -> 피드 상세
- [x] 관심글 -> 작품 피드
- [x] 취향 추천 -> 작품 정보
- [x] 소소픽 -> 작품 정보

**Comment by Guryss** [comment]
윤학오빠 작품 상세뷰 API 연결 후 작업 예정
