### ISSUE TITLE
[Design] MyPageView UI 구현

### ISSUE THREAD

**Issue by ena-isme** [Team-WSS/WSS-iOS#27]
## 🛠 Issue

MyPageView UI를 구현할 것입니다 !

## 📝 To-do

- [x] 상단 메인뷰 구현
- [x] 내 작품 상세뷰 구현
- [x]  캐릭터 선택뷰 구현
- [x] 기타 설정뷰 구현
- [x] 닉네임 변경뷰 구현
- [x] 팝업 모달 구현
