### ISSUE TITLE
[Fix] HomeView 내 1차 QA 실시간 반영 

### ISSUE THREAD

**Issue by Guryss** [Team-WSS/WSS-iOS#283]
## 📝 To-do

- [x] 수다글 viewWillAppearEvent로 이동
- [x] 관심글 UI 레이아웃 수정
- [x] 공지사항 썸네일 이미지 변경
- [x] icComment 이미지 변경 및 FeedReactView 컬러 수정
