### ISSUE TITLE
[Network&Feat] 온보딩 API 연결 및 기능 구현

### ISSUE THREAD

**Issue by Naknakk** [Team-WSS/WSS-iOS#291]
## 📝 To-do

- [ ] 닉네임 뷰 기능 구현
- [ ] 닉네임 뷰 API 붙이기
- [ ] 성별 및 출생연도 기능 구현
- [ ] 선호장르 기능 마무리
- [ ] 온보딩 완료 API 붙이기
