### ISSUE TITLE
[Feat] 상세탐색뷰 기능 2차 구현

### ISSUE THREAD

**Issue by Guryss** [Team-WSS/WSS-iOS#300]
## 🛠 Issue
- 상세탐색 기능 2차 구현합니다. 

## 📝 To-do

- [x] NotificationCenter 쌓이는 이슈 수정
- [x] 컬렉션뷰 itemSelected 기능
- [x] 상단바 클릭 시 다시 모달 뜰 수 있도록
- [x] 무한스크롤 
- [x] 검색결과 없을 때 UI
