### ISSUE TITLE
[Fix] FeedDetailView 2차 QA 대응

### ISSUE THREAD

**Issue by Guryss** [Team-WSS/WSS-iOS#350]
## 🛠 Issue
- FeedDetailView 2차 QA 대응합니다.

## 📝 To-do

- [ ] 댓글 2번 작성되는 이슈 수정
- [ ] 좋아요 터치영역 수정
- [ ] 다른 유저 프로필 클릭 시 이벤트 세팅
