### ISSUE TITLE
[Fix] FeedEditView, FeedDetailView 피드탭 2차 QA 대응

### ISSUE THREAD

**Issue by hyowon612** [Team-WSS/WSS-iOS#353]
## 🛠 Issue

FeedEditView, FeedDetailView 피드탭 2차 QA 대응
## 📝 To-do

- [x] placeholder 내용 수정
- [x] 피드 작성 후 토스트
- [x] 스포일러 신고 모달 라이팅 변경
