### ISSUE TITLE
[Feat] MyPageView 기능 추가 구현

### ISSUE THREAD

**Issue by ena-isme** [Team-WSS/WSS-iOS#364]
## 📝 To-do

- [x] 내 페이지와 타인 페이지 구분
- [x] 타인일 시 내 활동 비었을 때 구분
- [x] 차단하기 API 구현
- [x] blockVC 수정
- [x] 탈퇴한 유저 처리
- [x] 차단하기 토스트메세지
- [x] animation 효과 제거
