### ISSUE TITLE
[Network] RecordView API 연결

### ISSUE THREAD

**Issue by chetseoo** [Team-WSS/WSS-iOS#37]
## 🛠 Issue

- 기록뷰를 서버와 연결합니다 !

## 📝 To-do

- [X] 서버통신 성공
- [X] TableView와 데이터 바인딩 by Rx
- [X] 기록이 없을 때, 있을 때 분기처리 
- [ ] 무한스크롤 구현 by Rx
