### ISSUE TITLE
[Feat] RegisterNormal 기본적인 기능 구현

### ISSUE THREAD

**Issue by Naknakk** [Team-WSS/WSS-iOS#48]
## 🛠 Issue

RegisterNormal View의 아직 남아있는 기본적인 기능 구현을 진행합니다.

## 📝 To-do

- [x] 읽기 상태에 따른 뷰 변화
- [x] DatePicker를 이용해 읽은 기간 설정
- [x] PlatformButton WebView 연결
