### ISSUE TITLE
[Network] MyPageView API 연결

### ISSUE THREAD

**Issue by ena-isme** [Team-WSS/WSS-iOS#55]
## 🛠 Issue
MyPageView API 연결

## 📝 To-do

- [x] 유저정보 조회 API
- [x] 아바타 정보 조회 API
- [x] 대표 아바타 변경 API
- [x] 유저 닉네임 변경 API
