### ISSUE TITLE
[Network] 네트워크 초기 설정 추가 

### ISSUE THREAD

**Issue by chetseoo** [Team-WSS/WSS-iOS#58]
## 🛠 Issue

- 네트워크 초기 설정 추가합니다 . . .

## 📝 To-do

- [ ] config 파일 수정
- [ ] Networking -> Bundle로 묶기
- [ ] APIConstant파일에 testTokenHeader 추가 
- [ ] info.plist에 http 통신 허용 추가
