### ISSUE TITLE
[Design] Home, Search, RecordView UI Detail 구현

### ISSUE THREAD

**Issue by chetseoo** [Team-WSS/WSS-iOS#79]
## 🛠 Issue

- 제가 담당한 Home, Search, RecordView UI를 디테일하게 구현합니다 .

## 📝 To-do

- [ ] Home, Search 간 navigationBar 연결 구현
- [X] 모든 뷰에 행간, 자간 익스텐션 적용
- [X] SearchView 탭바 그림자 제거
