### ISSUE TITLE
[Fix] LibraryView 1차 QA 반영

### ISSUE THREAD

**Issue by ena-isme** [Team-WSS/WSS-iOS#86]
## 📝 To-do

- [x] 별점이 0.0일 때 노출 X
- [x] 상황별 데이터 분기처리
- [x] 탭바 터치처리와 하단 바추가
- [x] 서재뷰 NULL 일때 화면 구현
- [x] 책 개수 표시
- [ ] 리스트 정렬 구현
- [ ] 무한 스크롤
