### ISSUE TITLE
[Fix] RegisterView 1차 QA 반영

### ISSUE THREAD

**Issue by Naknakk** [Team-WSS/WSS-iOS#89]
## 🛠 Issue
RegisterView 1차 QA 반영

## 📝 To-do

- [x] 종료 날짜가 현재 날짜를 넘지 못하게
- [x] 키워드 뷰 제거
- [x] 작품 보러가기 뷰 간격 조정
- [x] 로띠 파일 추가, 등록 로띠 교체
- [x] datePicker 중앙 정렬
- [x] Success 화면에서 메모로 바로 가는 버튼 (효원이가 해줬당)
- [x] 수정완료 두번 누를 수 없도록 처리 (후순위)
