### ISSUE TITLE
[Fix] SearchView 1차 QA 반영

### ISSUE THREAD

**Issue by chetseoo** [Team-WSS/WSS-iOS#91]
## 🛠 Issue

- 1차 QA 이후 SearchView 수정합니다. 

## 📝 To-do

- [X] SearchView로 넘어왔을 때 키보드 올라가도록 
- [X] SearchView placeHolder 없애기
- [X] 키보드 엔터 누르면 키보드 다시 내려가도록
