### ISSUE TITLE
[Fix] RecordView 1차 QA 반영

### ISSUE THREAD

**Issue by chetseoo** [Team-WSS/WSS-iOS#93]
## 🛠 Issue

- RecordView 1차 QA 반영하여 수정합니다.

## 📝 To-do

- [X] 기록 1->0개 될때 안뜨는 이슈 ,,, : isHidden 처리해보기
- [X] 기록 없을 때 기록하기 버튼 기능 구현
- [X] 기록 정렬 뷰 버튼 붙이기
- [X] 기록 정렬 기능
