### ISSUE TITLE
[Fix] HomeView 1차 QA 반영

### ISSUE THREAD

**Issue by Naknakk** [Team-WSS/WSS-iOS#94]
## 🛠 Issue
HomeView 1차 QA 반영

## 📝 To-do

- [x] 상단 검색창 line layout 수정
- [X] homeView 기기대응 (ScrollView)
- [x] 서버에서 받아서 아바타이미지 변경

**Comment by chetseoo** [comment]
good
