### ISSUE TITLE
[Fix] MyPageView 1차 QA 반영

### ISSUE THREAD

**Issue by ena-isme** [Team-WSS/WSS-iOS#98]
## 🛠 Issue
[Fix] MyPageView 1차 QA 반영

## 📝 To-do

- [x] 닉네임 글자수 10자 맞추기
- [x] 완료 버튼 활성화 분기처리
- [x] 캐릭터 오류
- [x] 캐릭터 해금 모션 처리
- [x] 로그아웃, 이메일, 회원 탈퇴 없애기
- [x] 인스타 연결
